-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 15:44:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_restaurante` DEFAULT CHARACTER SET utf8 ;
USE `db_restaurante` ;

-- -----------------------------------------------------
-- Table `db_restaurante`.`tb_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`tb_funcionarios` (
  `id_Funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`id_Funcionario`),
  UNIQUE INDEX `id_Funcionario_UNIQUE` (`id_Funcionario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`tb_produtos` (
  `id_produto` INT NOT NULL,
  `nome_prato` VARCHAR(45) NOT NULL,
  `descricao_prato` VARCHAR(100) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`tb_vendas` (
  `fk_funcionario` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `mesa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fk_funcionario`, `fk_produto`),
  INDEX `fk_tb_funcionarios_has_tb_produtos_tb_produtos1_idx` (`fk_produto` ASC) VISIBLE,
  INDEX `fk_tb_funcionarios_has_tb_produtos_tb_funcionarios_idx` (`fk_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_funcionarios_has_tb_produtos_tb_funcionarios`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `db_restaurante`.`tb_funcionarios` (`id_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_funcionarios_has_tb_produtos_tb_produtos1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `db_restaurante`.`tb_produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
